-- SQL INSERT Queries for 35 Materials & Chemicals (Station ID 1)

INSERT IGNORE INTO `inventory_materials` (`station_id`, `catalog_number`, `name`, `category`, `unit`, `opening_qty`, `opening_date`, `minimum_qty`, `version`, `created_at`, `updated_at`) VALUES
(1, 1, 'Heavy Duty Exterior Washing Liquid', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 2, 'Ceramic & Stainless Steel Toilet Fittings Cleaning Agent', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 3, 'Glass Cleaning Agent', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 4, 'PVC Floor Cleaning Agent', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 5, 'Air Freshener', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 6, 'Liquid Hand Soap (Hand Wash)', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 7, 'Cleaning Agent for Removing Old Sticker, Glue Marks etc.', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 8, 'Stainless Steel Polish', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 9, 'Banister Brush', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 10, 'Bucket (15 L + 5 L)', 'Equipment', 'sets', 0, NULL, 0, 1, NOW(), NOW()),
(1, 11, 'Foot Broom Head with Bristles', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 12, 'Polypropylene Bristle Brush', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 13, 'Suitable Broom', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 14, 'Disposable Bag (29 × 39)', 'Consumable', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 15, 'Floor Mopper', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 16, 'Mopper Cloth', 'Consumable', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 17, 'Microfiber Cloth', 'Consumable', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 18, 'Fiber Hand Held Brush (Round Type)', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 19, 'Floor Squeezer', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 20, 'Window Squeezer', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 21, 'Bottle with Spray Gun', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 22, 'Super Absorbent Floor Mopper', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 23, 'Squeeze Brush', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 24, 'Toilet Commode Brush', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 25, 'Carpet Brush', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 26, 'Upholstery Cleaning Brush', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 27, 'Sponge Duster (Yellow)', 'Consumable', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 28, 'Disposable Bag for Dustbin (19 × 21)', 'Consumable', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 29, 'Disinfectants', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 30, 'Mosquito Repellent Spray', 'Chemical', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 31, 'Tissue Paper for Western AC Coach Toilet', 'Consumable', 'rolls', 0, NULL, 0, 1, NOW(), NOW()),
(1, 32, 'Deodorant Stick/Cake for Each Toilet in AC Coaches', 'Consumable', 'pcs', 0, NULL, 0, 1, NOW(), NOW()),
(1, 33, 'Painted Surface Cleaning Agent', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 34, 'Laminated Plastic Sheet & Berth Rexine Cleaner', 'Chemical', 'L', 0, NULL, 0, 1, NOW(), NOW()),
(1, 35, 'Window Glass Squeezer', 'Equipment', 'pcs', 0, NULL, 0, 1, NOW(), NOW());

INSERT IGNORE INTO `inventory_seeded_stations` (`station_id`, `seeded_at`) VALUES (1, NOW());
