<?php
declare(strict_types=1);

// Reference photograph order. Spelling is normalized; similar tools remain separate.
return [
    ['Heavy Duty Exterior Washing Liquid', 'Chemical', 'L'],
    ['Ceramic & Stainless Steel Toilet Fittings Cleaning Agent', 'Chemical', 'L'],
    ['Glass Cleaning Agent', 'Chemical', 'L'],
    ['PVC Floor Cleaning Agent', 'Chemical', 'L'],
    ['Air Freshener', 'Chemical', 'L'],
    ['Liquid Hand Soap (Hand Wash)', 'Chemical', 'L'],
    ['Cleaning Agent for Removing Old Sticker, Glue Marks etc.', 'Chemical', 'L'],
    ['Stainless Steel Polish', 'Chemical', 'L'],
    ['Banister Brush', 'Equipment', 'pcs'],
    ['Bucket (15 L + 5 L)', 'Equipment', 'sets'],
    ['Foot Broom Head with Bristles', 'Equipment', 'pcs'],
    ['Polypropylene Bristle Brush', 'Equipment', 'pcs'],
    ['Suitable Broom', 'Equipment', 'pcs'],
    ['Disposable Bag (29 × 39)', 'Consumable', 'pcs'],
    ['Floor Mopper', 'Equipment', 'pcs'],
    ['Mopper Cloth', 'Consumable', 'pcs'],
    ['Microfiber Cloth', 'Consumable', 'pcs'],
    ['Fiber Hand Held Brush (Round Type)', 'Equipment', 'pcs'],
    ['Floor Squeezer', 'Equipment', 'pcs'],
    ['Window Squeezer', 'Equipment', 'pcs'],
    ['Bottle with Spray Gun', 'Equipment', 'pcs'],
    ['Super Absorbent Floor Mopper', 'Equipment', 'pcs'],
    ['Squeeze Brush', 'Equipment', 'pcs'],
    ['Toilet Commode Brush', 'Equipment', 'pcs'],
    ['Carpet Brush', 'Equipment', 'pcs'],
    ['Upholstery Cleaning Brush', 'Equipment', 'pcs'],
    ['Sponge Duster (Yellow)', 'Consumable', 'pcs'],
    ['Disposable Bag for Dustbin (19 × 21)', 'Consumable', 'pcs'],
    ['Disinfectants', 'Chemical', 'L'],
    ['Mosquito Repellent Spray', 'Chemical', 'pcs'],
    ['Tissue Paper for Western AC Coach Toilet', 'Consumable', 'rolls'],
    ['Deodorant Stick/Cake for Each Toilet in AC Coaches', 'Consumable', 'pcs'],
    ['Painted Surface Cleaning Agent', 'Chemical', 'L'],
    ['Laminated Plastic Sheet & Berth Rexine Cleaner', 'Chemical', 'L'],
    ['Window Glass Squeezer', 'Equipment', 'pcs'],
];
